name = "Reactions"
uuid = "2bef66ca-a4f7-11e8-2c3b-8770c8b1effa"
authors = ["Ryan Spangler <ryan.spangler@gmail.com>"]
version = "0.1.0"

[deps]
Iterators = "a4bce56a-f44e-563f-a45f-5312daf41243"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
